version: 0.2

env:
  parameter-store:
    ECR_REPOSITORY_URI: /myapp/ecr/repository-uri
    TMDB_API_KEY: /ecr/api/key
  variables:
    AWS_DEFAULT_REGION: us-east-1

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - node --version
      - echo "Node installed"
  pre_build:
    commands:
      - npm install
      - echo "Dependencies installed"
      - echo "ECR Repository URI is $ECR_REPOSITORY_URI"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI
      - echo "ECR login successful"
  build:
    commands:
      - docker build . -t $ECR_REPOSITORY_URI:latest --build-arg TMDB_V3_API_KEY=$TMDB_API_KEY
      - echo "Docker build completed"
  post_build:
    commands:
      - echo "Pushing image to ECR"
      - docker push $ECR_REPOSITORY_URI:latest
      - echo "Docker push completed"

artifacts:
  files:
    - appspec.yml
    - scripts/**/*