version: 0.2

env:
  parameter-store:
    ECR_REPOSITORY_URI: netflix-clone
    KEY: /ecr/api/key

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - node --version
      - echo "installed node "
    # steps:
  pre_build:
    commands:
      - npm install
      - echo "dependencies installed"
  build:
    commands:
      - docker build . -t $ECR_REPOSITORY_URI:latest --build-arg TMDB_V3_API_KEY=$KEY
  post_build:
    commands:
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI
      - docker push $ECR_REPOSITORY_URI:latest
artifacts:
  files:
    - "**/*"
  base-directory: "./"
  name: build-artifact-name
  type: zip
  discard-paths: no
